# Generated by Django 5.2 on 2025-04-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='numCompletions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='forgotCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='rememberCount',
            field=models.IntegerField(default=0),
        ),
    ]
