# Generated by Django 5.2 on 2025-04-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_box_numcompletions_card_forgotcount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='boxId',
            field=models.IntegerField(default=0),
        ),
    ]
