# Generated by Django 5.2 on 2025-05-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_boxid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(default='NONE', max_length=300),
        ),
        migrations.AlterField(
            model_name='box',
            name='user',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
