# Generated by Django 5.2 on 2025-05-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_box_name_alter_box_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=2000, unique=True)),
                ('count', models.IntegerField(default=100)),
                ('lastUpdated', models.DateTimeField()),
                ('hasHitLimitOnce', models.BooleanField(default=False)),
            ],
        ),
    ]
